### ISSUE TITLE
Not using the event_selector variable

### ISSUE THREAD

**Issue by iRitiLopes** [clouddrove/terraform-aws-cloudtrail#1]
When is passed the Event selector variable with a list of maps, the module doesn't even use the values, and the trail is not created for all lambda resources and/or s3 objects

**Comment by anmolnagpal** [comment]
Hello @iRitiLopes 

Thanks, we are looking into it. will update asap.

**Comment by sohanyadav** [comment]
@iRitiLopes  with 0.15  version we have added the `event_selector` variable with dynamic. 

Hope you are enjoying yourself with CloudDrove modules.
