### ISSUE TITLE
cloudtrail Name is provided 

### ISSUE THREAD

**Issue by salman-cheema** [clouddrove/terraform-aws-cloudtrail#14]
I have set the name in module for the cloudtrail but still getting this error:

`Error: Error creating CloudTrail: InvalidTrailNameException: Trail name cannot be blank!`

I have tried different versions of module and upgraded my terraform version but no success.

**Comment by sohanyadav** [comment]
@salman-cheema  i think you are misiing  this value 
`label_order             = ["name", "environment"] `

**Comment by sohanyadav** [comment]
@salman-cheema  I'm going to close this Issue because looks like you missed the  `label_order`  variable 

Hope You are enjoying CloudDrove Open source Modules.
